// Tint.green('green');
// Tint.blue('blue');
// Tint.red('red');
// Tint.orange('orange');
// Tint.bgGreen('bgGreen');
// Tint.bgBlue('bgBlue');
// Tint.bgRed('bgRed');
// Tint.bgOrange('bgOrange');
// Tint.bold('bold');
// Tint.underline('underline');
// Tint.sm('sm');
// Tint.xl.green.bold.underline('xl');
// Tint.bold.lg.blue('big bold blue');